name: Pull Request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn test

      - run: yarn build
